### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/meteor-blaze-bs4#20]
https://getbootstrap.com/docs/4.2/components/toasts/

**Comment by jamgold** [comment]
I have a working implementation of BS4 Toast. Should I create a RP?

**Comment by jankapunkt** [comment]
Hey @jamgold thanks, that would be really great!

Please note, that this package supports sync and async (controlled via environment flags) loading of the compoents.

* Therefore, please add the component the the [`BlazeBs4`](https://github.com/jankapunkt/meteor-blaze-bs4/blob/master/blaze-bs4/blaze-bs4.js) export as well as to the [sync file list](https://github.com/jankapunkt/meteor-blaze-bs4/blob/master/blaze-bs4/package.js#L23).
* Please add some simple unit tests, if possible.
* There is no need to update the examples, I will do that later.
* You can get some orientation by looking at the code of the other components.

**Comment by jamgold** [comment]
> Please add some simple unit tests, if possible

I will look into that, but not sure how that can be done. This will only work dynamically in a browser
