### ISSUE TITLE
jumbotron component needs to load BlazeBs4.jumnbotron.load()

### ISSUE THREAD

**Issue by jamgold** [jankapunkt/meteor-blaze-bs4#29]
**Describe the bug**
In order to dynamically load the jumbotron component, one has to `BlazeBs4.jumnbotron.load()`, spelled *jumnbotron* (extra n), which is not very intuitive, nor documented.

**To Reproduce**
1. use BlazeBs4.jumbotron.load() fails

**Expected behavior**
use BlazeBs4.jumbotron.load() instead of BlazeBs4.jumnbotron.load() 

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6
 - Browser firefox 
 - Version 72.0.1

**Comment by jankapunkt** [comment]
You're right, this is really annoying. Would you like to rename it and provide a PR?

**Comment by jamgold** [comment]
Sure, how do I create a PR?

**Comment by jankapunkt** [comment]
1. fork the project
2. clone it to local
3. create a new branch
4. make changes, commit changes
5. push new branch
6. go to this site, section pull request and it should show you the available branches from your fork to pull in, select the one you created in 3.

If you you get stuck at any stage you can just copy the term behind the number and search it in the GitHub help (the GitHub help is the best help on Git ever)

**Comment by jankapunkt** [comment]
Fixed via #30 and published in 0.15.4, please check if everything is okay and feeld free to reopen if there is any issue on your side left.
