### ISSUE TITLE
Disabled and Active properties for Link component not implemented

### ISSUE THREAD

**Issue by tushar13293** [jankapunkt/meteor-blaze-bs4#36]
**Is your feature request related to a problem? Please describe.**
The link component doesn't include **Disabled** and **Active** attributes

**Comment by jankapunkt** [comment]
`disabled` property is implemented in the new  `0.16.1` release, please update your packages if not automatically update

**Comment by jankapunkt** [comment]
`active` is missing and will be implemented asap

**Comment by jankapunkt** [comment]
Okay active links only appear in `nav` and `navbar` and they are already covered using `navlink` so please use `> navlink` in these situations: https://jankapunkt.github.io/meteor-blaze-bs4/about -> navbars
